name: Submit a Server
description: Submit an MCP server to the registry
title: "[Server] "
labels: ["new-server"]
body:
  - type: input
    id: name
    attributes:
      label: Server Name
      placeholder: e.g., GitHub MCP Server
    validations:
      required: true
  - type: input
    id: repository
    attributes:
      label: Repository URL
      placeholder: https://github.com/...
    validations:
      required: true
  - type: dropdown
    id: transport
    attributes:
      label: Transport Type
      options:
        - stdio (local command)
        - http (remote URL)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What does this server do?
    validations:
      required: true
  - type: input
    id: install_command
    attributes:
      label: Install Command (for stdio)
      placeholder: e.g., npx -y @example/mcp-server
  - type: input
    id: url
    attributes:
      label: Server URL (for http)
      placeholder: https://api.example.com/mcp
  - type: checkboxes
    id: categories
    attributes:
      label: Categories
      options:
        - label: Developer Tools
        - label: Version Control
        - label: Cloud Services
        - label: Productivity
        - label: Database
        - label: Search & Web
        - label: Communication
        - label: File System
        - label: Documentation
        - label: AI & Machine Learning
